import pathlib
p = pathlib.Path("/home/perieteanu/projects/rite/docs/DECISIONS.yaml")
text = p.read_text(encoding="utf-8")
before = len(text.encode("utf-8"))

entry = '''
  - id: d-one-home-for-the-stage-mapping
    date: "2026-09-10"
    title: "The stage mapping is generated into hand-written files, and a guard stops new copies"
    context: >
      On 2026-09-10 the stage->artifact mapping was hand-copied into README.md,
      template/.rite.yaml and CLAUDE.md on the same day the mechanism it describes was built —
      c-stage-table-duplicated-in-three-places. Building the fix found a FOURTH copy the concern
      had not counted, in ROADMAP.current_state.
    decision: >
      BOTH halves, not one. (1) spec/project-standard.yaml gains `generated_blocks`, and
      `render-standard.py --blocks` fills a marker-fenced region inside README.md and
      template/.rite.yaml from artifacts[].required_from_stage; `--blocks --check` is a gate.
      (2) scripts/test-stage-table-guard.py fails when three stage names appear near three
      artifact names outside such a block, in the live rewrite-only documents.
      CLAUDE.md's copy and ROADMAP's were DELETED rather than generated.
    rationale:
      - >
        GENERATION AND A GUARD ANSWER DIFFERENT QUESTIONS, which is why one alone was not
        enough. Generation removes drift from the copies that EXIST. It is structurally blind to
        a copy that does not exist yet: a new paragraph enumerating the stages is not drift from
        anything, so --blocks --check would never look at it. Four copies appeared in one day
        by exactly that route.
      - >
        REMOVING A COPY BEATS MECHANISING ONE. CLAUDE.md stated the mapping as a prose sentence
        mid-bullet; a marker block there would have forced a table into a document that is
        dense prose by design. Fewest copies wins, and the bullet now describes the mechanism
        instead of restating the data.
      - >
        THE GUARD READS ONLY WHAT MAY LEGALLY BE EDITED. LOG.md, DECISIONS.yaml and ROADMAP's
        milestones zone are append-only records of what was true then. A gate that fails on a
        file nobody may fix is a gate that gets switched off within a week, which is the same
        argument that keeps a clock out of generated output.
      - >
        THE TARGET LIST LIVES IN THE YAML, not in the renderer. A path list that exists only in
        code is a hardcoded value with no human-visible home, and this file is already the
        authority for what is generated.
    evidence:
      - "The README table generated BYTE-IDENTICAL on the first run. template/.rite.yaml did not: its hand-written copy abbreviated `docs/MISSION.md` to `MISSION`. The copies had already begun to diverge."
      - "Both gates were proved to FAIL before being trusted — a row was added to the README table, and a fifth copy was pasted into docs/MISSION.md. Each was restored from a file copy, never `git checkout`."
      - "The guard found the fourth copy nobody had counted, in ROADMAP.current_state."
    corrects: >
      A FALSE PREMISE IN d-stage-advances-when-the-repo-goes-public, recorded here because that
      entry is append-only and stays as written. Its context says LICENSE "reports NA on the one
      project that actually ships a LICENSE". It does not, and did not then. Verified 2026-09-10
      by running the checker against a `stage: shipped` copy of this tree: LICENSE is GREEN at
      `build` and GREEN at `shipped`, because `required_from_stage` gates whether an artifact is
      DEMANDED, not whether it is CHECKED when present. The stage decides only whether a MISSING
      LICENSE is RED or NA. CLAUDE.md carried the same error and, being rewrite-only, was
      corrected in place. The DECISION that entry reached is unaffected — advancing the stage on
      publication is still right, for the reasons it gives.
    chosen_by_user: true
    proposed_by: claude
'''

p.write_text(text.rstrip("\n") + "\n" + entry, encoding="utf-8", newline="\n")
print(f"DECISIONS.yaml: {before} -> {len(p.read_bytes())} bytes")
