import datetime, pathlib
p = pathlib.Path("/home/perieteanu/projects/rite/LOG.md")

entries = [
 ("fix", "PUBLISHED. github.com/perieteanu/rite is PUBLIC as of today, main in full with LOG.md included per d-publish-main-in-full-no-export. stage advanced build -> shipped in the same commit. Verified two ways: gh repo view says PUBLIC and the API says private:false. CI green on the publishing commit across ubuntu, macos and windows"),
 ("fix", "THE PUBLISH CHECKLIST'S THIRD ACT RESTED ON A FALSE PREMISE and verifying beat performing. It said the LICENSE check 'currently reports NA' and to confirm it went GREEN not RED on the stage flip. It was ALREADY GREEN at build and always had been: required_from_stage gates whether an artifact is DEMANDED, not whether it is CHECKED when present. The stage decides only whether a MISSING LICENSE is RED or NA. Settled by running the checker against a stage: shipped copy of the tree before touching anything"),
 ("fix", "Two documents carried that false claim. CLAUDE.md is rewrite-only and was corrected in place; d-stage-advances-when-the-repo-goes-public is append-only so the correction went into the NEW decision as a `corrects:` field. The decision it reached is unaffected — advancing the stage on publication is still right, for the reasons it gives"),
 ("add", "python_invocation_differs now has a check that fails. It was declared in the spec and enforced by NOTHING — a grep for its id across every .py and .yaml returned one hit, the spec declaring it — while two shipped SKILL.md prompts violated it. That is the rule's own worst case: a skill prompt is a command a Windows user's agent runs. Six violations on the first run, all predicted"),
 ("note", "The rule needed a line no AST can draw, since there is no syntax tree for prose. Drawn where the rule actually cares: `python3` NAMED is a mention ('Windows has no python3'), `python3` INVOKED WITH A PATH is a command a reader copies. Only the second fails. That is why CONVENTIONS.md may state the rule and rite.sh may probe all three names without either being special-cased into an exemption that would also hide a real violation in the same file"),
 ("add", "Both shims gain a `check` action plus argument passthrough, so no prompt has to name an interpreter. An explicit action table replaces ${action//-/_}: the checker is rite-check.py with a HYPHEN, and adding a rite_check.py beside it to make the mangle work would be a trap for every future reader"),
 ("fix", "c-stage-table-duplicated-in-three-places settled the day after it opened, taking BOTH halves of its proposal because they answer different questions. Generation removes drift from the copies that EXIST; a guard stops the next one, which generation structurally cannot, because a fresh enumeration is not drift from anything. render-standard.py gains --blocks; test-stage-table-guard.py is the guard. Gate count 9 -> 11"),
 ("note", "The concern UNDERSTATED itself twice. It said three places and there were FOUR — ROADMAP.current_state carried the mapping too and nobody had noticed. And the README table generated BYTE-IDENTICAL on the first run while template/.rite.yaml did NOT, because its hand-written copy abbreviated docs/MISSION.md to MISSION. The copies had already begun to diverge, silently"),
 ("note", "Both new gates were proved to FAIL before being trusted — a row added to the README table, a fifth copy pasted into MISSION.md — each restored from a file copy, never git checkout. A guard that has never failed has not been tested"),
 ("add", "c-pattern-paths-are-matched-literally opened, HIGH, found by archiving this session's plan. plan_copy declares path 'docs/PLAN-YYYY-MM-DD-<slug>.md' and rite-check.py compares it with exists_exactly, a literal case-sensitive test. With TWO real plan files on disk it still prints 'not present'. filename_matches_canonical has never run against a plan and cannot"),
 ("add", "c-rite-ps1-unreachable-in-production opened, HIGH. hooks.json names `bash rite.sh` for all three events and never references rite.ps1. CI invokes the .ps1 DIRECTLY, so it passed on windows-latest — a green test over an unreachable code path, which is the most expensive kind of false assurance. The spec's coverage list claims a Windows-without-Git-Bash row that no user can reach"),
 ("add", "c-readme-sample-output-is-a-copy opened, low. The README's quoted sample run restates the stage mapping and the guard exempts fenced blocks on purpose — a guard that fires on quoted output gets switched off before it is fixed. Exempt by design, recorded rather than hidden"),
 ("note", "THREE MEMBERS OF ONE FAMILY IN A SINGLE DAY: a rule declared and enforced by nothing, a shim tested but unreachable in production, and a test whose artifact can never be found. All three READ AS COVERED. That is a sharper failure than a visible gap, and it is the same shape as the project's founding complaint one level up"),
 ("fix", "Corrected a stale spec claim found while editing the neighbouring block: portability said 'none of this has run on a real Windows or macOS machine', false since the matrix ran. What IS still unverified is narrower and worse, and is now written there"),
]

lines = []
for kind, text in entries:
    now = datetime.datetime.now()
    stamp = now.strftime("%d-%m-%Y %H:%M:%S")
    dow = ["Mon","Tue","Wed","Thu","Fri","Sat","Sun"][now.weekday()]
    lines.append(f"{stamp} | {dow} | rite | [{kind}] {text}")

before = len(p.read_bytes())
with p.open("a", encoding="utf-8", newline="\n") as fh:
    fh.write("\n".join(lines) + "\n")
print(f"LOG.md: {before} -> {len(p.read_bytes())} bytes, +{len(lines)} entries")
